projeto2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("webapp.urls")),
]

webapp/urls.py
# URLs

# Imports
from django.urls import path
from .views import HomeView

# Nome da app
app_name = "webapp"

# URL da página home
urlpatterns = [path("", HomeView.as_view(), name="home-view")]

webapp/views.py
# Módulos Para Mostrar o Resultado na Intrerface Web

# Imports
import pickle
import pandas as pd
from django.shortcuts import render
from django.views import View

# Classe
class HomeView(View):

    # Método Get
    def get(self, request, *args, **kwargs): 
        return render(request, "index.html")

    # Método Post
    def post(self, request, *args, **kwargs):
        
        # Obtém os dados do formulário
        indice_bolsa_sp = int(request.POST.get("indice_bolsa_sp"))
        inflacao_alta = int(request.POST.get("inflacao_alta"))
        taxa_desemprego = int(request.POST.get("taxa_desemprego"))
        taxa_juros = int(request.POST.get("taxa_juros"))

        # Carrega o modelo
        pickle_in = open("webapp/modelos/modelo_v1.pickle", "rb")
        linear = pickle.load(pickle_in)

        # Faz as previsões
        prediction = linear.predict(pd.DataFrame([[indice_bolsa_sp, inflacao_alta, taxa_desemprego, taxa_juros]], columns = ["indice_bolsa_sp", "inflacao_alta", "taxa_desemprego", "taxa_juros"]))
        prediction_point = prediction[0]

        # Classificação (cut-off)
        if prediction_point >= 1.35:
            predict = "A Tendência do Mercado é de Alta!"
        else:
            predict = "A Tendência do Mercado é de Baixa!"
        
        # Passando o resultado para o arquivo html
        context = {"prediction_point":prediction_point, "predict":predict}

        return render(request, "resultado.html", context)


        

webapp/templates/index.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Projeto 2</title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'webapp:home-view' %}">Machine Learning Web App</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'webapp:home-view' %}">Home<span class="sr-only">(current)</span></a>
            </li>
          </ul>
        </div>
      </nav>

      <div style="margin: 20px;"></div>

      {% block body %}

      <div class="container">
       <div class="jumbotron">
        <h1 class="display-4">Projeto 2</h1>
        <hr class="my-4">
        <h5 class="display-5">Prevendo o Comportamento do Mercado Financeiro</h5>
        <h5 class="display-5">Selecione as opções abaixo e clique no botão Fazer Previsão</h5>
       </div>
      </div>

      <div class="container">
        <form method="post">
          {% csrf_token %}
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="inputState">Índice Bolsa SP</label>
              <select id="inputState" class="form-control" name="indice_bolsa_sp" required>
                <option value="">Selecione...</option>
                <option value="1">Menos de 0</option>
                <option value="2">De 0 a 3</option>
                <option value="3">De 3 a 6</option>
                <option value="4">De 6 a 9</option>
                <option value="5">Acima de 9</option>
              </select>
            </div>
            <div class="form-group col-md-6">
              <label for="inputState">A Inflação Está Alta (Acima de 4%)?</label>
              <select id="inputState" class="form-control" name="inflacao_alta" required>
                <option value="">Selecione...</option>
                <option value="0">Não</option>
                <option value="1">Sim</option>
              </select>
            </div>
          </div>
          <div class="form-row">
            <div class="form-group col-md-6">
              <label for="inputState">Taxa de Desemprego</label>
              <select id="inputState" class="form-control" name="taxa_desemprego" required>
                <option value="">Selecione...</option>
                <option value="1">Igual a 0</option>
                <option value="2">De 0 a 2</option>
                <option value="3">De 2 a 4</option>
                <option value="4">De 4 a 6</option>
                <option value="5">De 6 a 8</option>
                <option value="5">De 8 a 10</option>
                <option value="7">Acima de 10</option>
              </select>
            </div>
            <div class="form-group col-md-6">
               <label for="inputState">Taxa de Juros</label>
              <select id="inputState" class="form-control" name="taxa_juros" required>
                <option value="">Selecione...</option>
                <option value="1">Igual a 0</option>
                <option value="2">De 0 a 1</option>
                <option value="3">De 1 a 2</option>
                <option value="4">de 2 a 3</option>
                <option value="5">Acima de 3</option>
              </select>
            </div>
          </div>
          <button type="submit" class="btn btn-primary">Fazer Previsão</button>
          </form>
      </div>

      {% endblock body %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/resultado.html
{% extends "index.html" %}

{% block body %}

<div class="container">
    <div class="jumbotron">
        <h1 class="display-4">Resultado da Previsão</h1>
        <hr class="my-4">
        <p>Previsão: {{ predict }}</p>
        <p class="lead">
          <a class="btn btn-primary btn-lg" href="{% url 'webapp:home-view' %}" role="button">Fazer Outra Previsão</a>
        </p>
    </div>
</div>

{% endblock body %}